/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 29-Jul-2022 13:52:36
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 41
 * 稳定     : 是
 * 线性相位   : 是 (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlabn\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 41;
const real32_T B[41] = {
  -0.001100884983, 0.002083054977, 0.001721346751,0.0002068621689, 0.004846923985,
  -7.242838111e-18,-0.008897772059,-0.0006883819005, -0.01002070215, -0.01965846494,
    0.01486194786,   0.0127013661, 0.002304187045,  0.06177522242,   0.0252294708,
   -0.04762808979,  0.02016398497, -0.09569679201,  -0.2822321057,  0.08792342246,
     0.4659163952,  0.08792342246,  -0.2822321057, -0.09569679201,  0.02016398497,
   -0.04762808979,   0.0252294708,  0.06177522242, 0.002304187045,   0.0127013661,
    0.01486194786, -0.01965846494, -0.01002070215,-0.0006883819005,-0.008897772059,
  -7.242838111e-18, 0.004846923985,0.0002068621689, 0.001721346751, 0.002083054977,
  -0.001100884983
};
